#ifndef __ACCELEROMETER_REFERANCE_VALUE_CALCULATION_H_
#define __ACCELEROMETER_REFERANCE_VALUE_CALCULATION_H_



void USER_Accelerometer_Referance_Value_Calculation(void);
#define NUMBER_OF_ACCELEROMETER_SAMPLES 10


#endif /* ACCELEROMETER_REFERANCE_VALUE_CALCULATION_H_ */
